apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastify
  template:
    metadata:
      labels:
        app: fastify
    spec:
      containers:
      - name: fastify
        image: leeorpe/my-fastify-app:latest
        ports:
        - containerPort: 3000