# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fastify-service
spec:
  type: NodePort
  selector:
    app: fastify
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  
    